### ISSUE TITLE
MAUI randomly crashing on Android when accessing static property updated on background thread

### ISSUE THREAD

**Issue by taublast** [taublast/DrawnUi.Maui#115]
Let's say we have this XAML:

```xml
  SelectedIndex="{Binding Source={x:Reference MainCarousel}, Path=SelectedIndex}"
```

If `SelectedIndex` was updated not on UI-thread we *sometimes* get a nice and very easily reproducible in one session crash, for me on Android:

```
11-09 11:09:52.678  1922  1922 E AndroidRuntime: FATAL EXCEPTION: main
11-09 11:09:52.678  1922  1922 E AndroidRuntime: android.runtime.JavaProxyThrowable: [System.Reflection.TargetInvocationException]: Exception has been thrown by the target of an invocation.
11-09 11:09:52.678  1922  1922 E AndroidRuntime:        at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Unknown Source:0)
11-09 11:09:52.678  1922  1922 E AndroidRuntime:        at System.Reflection.RuntimeMethodInfo.Invoke(Unknown Source:0)
11-09 11:09:52.678  1922  1922 E AndroidRuntime:        at System.Reflection.MethodBase.Invoke(Unknown Source:0)
11-09 11:09:52.678  1922  1922 E AndroidRuntime:        at Microsoft.Maui.Controls.BindingExpression+BindingExpressionPart.TryGetValue(Unknown Source:0)
11-09 11:09:52.678  1922  1922 E AndroidRuntime:        at Microsoft.Maui.Controls.BindingExpression.ApplyCore(Unknown Source:0)
11-09 11:09:52.678  1922  1922 E AndroidRuntime:        at Microsoft.Maui.Controls.BindingExpression.Apply(Unknown Source:0)
11-09 11:09:52.678  1922  1922 E AndroidRuntime:        at Microsoft.Maui.Controls.BindingExpression+BindingExpressionPart.<PropertyChanged>b__50_0(Unknown Source:0)
11-09 11:09:52.678  1922  1922 E AndroidRuntime:        at Microsoft.Maui.Dispatching.Dispatcher+<>c__DisplayClass4_0.<DispatchImplementation>b__0(Unknown Source:0)
11-09 11:09:52.678  1922  1922 E AndroidRuntime:        at Java.Lang.Thread+RunnableImplementor.Run(Unknown Source:0)
11-09 11:09:52.678  1922  1922 E AndroidRuntime:        at Java.Lang.IRunnableInvoker.n_Run(Unknown Source:0)
11-09 11:09:52.678  1922  1922 E AndroidRuntime:        at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(Unknown Source:0)
11-09 11:09:52.678  1922  1922 E AndroidRuntime:        at mono.java.lang.RunnableImplementor.n_run(Native Method)
11-09 11:09:52.678  1922  1922 E AndroidRuntime:        at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:31)
11-09 11:09:52.678  1922  1922 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:873)
11-09 11:09:52.678  1922  1922 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
11-09 11:09:52.678  1922  1922 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:193)
11-09 11:09:52.678  1922  1922 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6705)
11-09 11:09:52.678  1922  1922 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
11-09 11:09:52.678  1922  1922 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
11-09 11:09:52.678  1922  1922 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)
```

In this particular case I managed to avoid this bug by implementing an additional read-only property to use in bindings instead of SelectedProperty:

```csharp
    /// <summary>
    /// Will be updated on MainThread to safely work with bindings,
    /// this a read-only property returning SelectingIndex in a thread-safe way;
    /// </summary>
    public int SafeIndex
    {
        get
        {
            return SelectedIndex;
        }
    }
```

and then when `SelectedIndex` is changed on background thread I call: 

```csharp
        MainThread.BeginInvokeOnMainThread(() =>
        {
            OnPropertyChanged(nameof(SafeIndex));
        });
```

this eliminates the crash completely. 

BUT the goal is to investigate inside MAUI source code to fix this internally so that never happens to anyone.

This issue is to be moved to MAUI repo when I find a fix.

**Comment by taublast** [comment]
Locally it looks to be fixed with a try-catch over a base.OnPrpertyChange call in our override. The crash remains somewhere deep inside MAUI still...
