### ISSUE TITLE
Failing to set SkiaImage Source from StreamImageSource

### ISSUE THREAD

**Issue by taublast** [taublast/DrawnUi.Maui#136]
### Discussed in https://github.com/taublast/DrawnUi.Maui/discussions/135

<div type='discussions-op-text'>

<sup>Originally posted by **Agredo** November 25, 2024</sup>
I am playing around with this great library. But at the moment I am struggeling with this code: 
`<draw:Canvas VerticalOptions="Fill" HorizontalOptions="Fill">

<draw:SkiaImage VerticalOptions="Fill" HorizontalOptions="Fill" Source="{Binding Image, Converter={StaticResource Key=ByteArrayToImageSourceConverter}}"/>

</draw:Canvas>`
            
I am getting the error:

System.ArgumentNullException: Value cannot be null. (Parameter 'cacheKey')
   at EasyCaching.Core.ArgumentCheck.NotNullOrWhiteSpace(String argument, String argumentName)
   at EasyCaching.InMemory.DefaultInMemoryCachingProvider.BaseGet[T](String cacheKey)
   at EasyCaching.Core.EasyCachingAbstractProvider.Get[T](String cacheKey)
   at DrawnUi.Maui.Draw.SkiaImageManager.LoadImageManagedAsync(ImageSource source, CancellationTokenSource token, LoadPriority priority)
   at DrawnUi.Maui.Draw.SkiaImage.LoadImageManagedAsync(ImageSource source, CancellationTokenSource cancel, LoadPriority priority)
   at DrawnUi.Maui.Draw.SkiaImage.<>c__DisplayClass73_1.<<SetImageSource>g__LoadAction|1>d.MoveNext()
   
   Is it possible to bind a byte Array and a converter to ImageSource? 

Thank you :)</div>

**Comment by taublast** [comment]
Fixed with https://github.com/taublast/DrawnUi.Maui/pull/137
